ic-hep/GridPPDIRAC

- ConfigurationSystem/private/UsersAndGroupsAPI.py
- Core/Security/MultiVOMSService.py
> fix for when the soap service returns None instead of an empty list

- ConfigurationSystem/Agent/AutoBdii2CSAgent.py
- ConfigurationSystem/ConfigTemplate.cfg
- ConfigurationSystem/private/AddResourceAPI.py
This fixes issue ic-hep/DIRAC#3
@sfayer I'm initiating the pull request as I think this is basically there now baring any issues that arise when you test it. If something does show up just let me know.
> Auto fill CS from BDII info

- ConfigurationSystem/private/AddResourceAPI.py
commit 9259d081b9e130b52c7ce4fc67ba47912e327920 fixes ic-hep/DIRAC#44
@sfayer FYI as I've been quite busy I've put this fix in but haven't tested it so please test this branch before merging.
> JobListFile fix

- ConfigurationSystem/private/AddResourceAPI.py
This commit fixes https://github.com/ic-hep/DIRAC/issues/45 as it addresses the bug raised in comment https://github.com/ic-hep/DIRAC/issues/45#issuecomment-106489854
@sfayer please review and merge
> CE removal fix

- ConfigurationSystem/private/AddResourceAPI.py
This fixes https://github.com/ic-hep/GridPPDIRAC/issues/13
@sfayer please review and merge
> Change Algorithm for MaxTotalJobs and MaxWaitingJobs

- ConfigurationSystem/Agent/AutoBdii2CSAgent.py
- ConfigurationSystem/private/AddResourceAPI.py
This pull request fixes https://github.com/ic-hep/DIRAC/issues/49
@sfayer please review and merge
> Adding list of SEs to site config

- ConfigurationSystem/private/AddResourceAPI.py
This pull request fixes https://github.com/ic-hep/DIRAC/issues/48 as well as correcting the accounting and reporting of the number of changes in the AddResources tool
> Banned resources fix

- WorkloadManagementSystem/PilotAgent/pilotTools.py
This patch updates our version of the pilotTools.py in line with updates that have happened in DIRAC upstream
> Update the pilotTools.py

- ConfigurationSystem/private/UsersAndGroupsAPI.py
This pull request should fix https://github.com/ic-hep/DIRAC/issues/51
> Don't delete users if a VOMS server is down

- ConfigurationSystem/private/AddResourceAPI.py
This PR resolves ic-hep/DIRAC#63
@sfayer Please review/test/merge this when ready
> Adding Multi-Core Support

- WorkloadManagementSystem/Agent/SiteDirector.py
This PR add the defaulted processors argument in line with v6r15.
@sfayer please review and merge
> Add extra default option to _getPilotOptions

- ConfigurationSystem/private/AddResourceAPI.py
This pull request adds the following mappings with a fall back to `disk`
DBII AccessLatency | DIRAC config
------------ | -------------
online | disk
nearline | tape
and fixes https://github.com/ic-hep/DIRAC/issues/56
> Support for -tape SEs

- ConfigurationSystem/private/AddResourceAPI.py
Half of the fix for https://github.com/ic-hep/DIRAC/issues/53
> Accept older BDII fields when getting GlueVOInfo

- Core/Security/HTTPSClientUtils.py
- Core/Security/MultiVOMSService.py
fixes https://github.com/ic-hep/DIRAC/issues/74
@sfayer please review, test and merge
> Migrate from cert/key to SSL context with given CA cert path.

- ConfigurationSystem/private/AddResourceAPI.py
> Patch GlueCEPolicyMaxCPUTime if it is 2147483647

- ConfigurationSystem/private/AddResourceAPI.py
This fixes https://github.com/ic-hep/DIRAC/issues/75 part 2
> Blank Site VO list if state != production.

- ConfigurationSystem/private/AddResourceAPI.py
addresses first part of https://github.com/ic-hep/DIRAC/issues/75
> Allow VOs to be removed from sites when no longer supported.

- ConfigurationSystem/private/AddResourceAPI.py
This patch fixes https://github.com/ic-hep/DIRAC/issues/71.
modified:   ConfigurationSystem/private/AddResourceAPI.py
> Add XRootD protocol support to AutoDBII2CS agent.

- WorkloadManagementSystem/Service/MatcherHandler.py
- WorkloadManagementSystem/Service/__init__.py
Maps pilot platform (in DIRAC format) to a user friendly "user platform" for ticket ic-hep/DIRAC#76.
> Add mapping of "NodeCompatibility" to Matcher service.

- ConfigurationSystem/Agent/AutoBdii2CSAgent.py
- ConfigurationSystem/private/AddResourceAPI.py
This is the patch for ic-hep/DIRAC#54.
> Add support for sending a weekly "old SEs" e-mail.

- ConfigurationSystem/private/UsersAndGroupsAPI.py
- Core/Security/MultiVOMSService.py
This patch works by not attaching any DIRAC groups (VOs roles) to the user if the user is suspended from that VO. If the user ends up with no groups then they are deleted as they always have been.
This patch closes https://github.com/ic-hep/DIRAC/issues/69
> Remove banned users from Config.

- ConfigurationSystem/private/AddResourceAPI.py
This commit fixes https://github.com/ic-hep/DIRAC/issues/71.
> Fix XRootD support.

- .travis.yml
- FrameworkSystem/Agent/HelloWorldAgent_test.py
- pytest.ini
It's aptly name "HelloWorldAgent_test.py"
> travis is now in a state where it can run a dummy test 

- WorkloadManagementSystem/PilotAgent/pilotTools.py
moved from https://github.com/ic-hep/DIRAC/pull/82.
This closes https://github.com/ic-hep/DIRAC/issues/81
> Pilottools resync

- .travis.yml
Considering the tests only take 2 minutes anyway, this is probably overkill... I guess we'll have to do another pull request to test it (as this one will only populate the cache the first time).
> Try enabling travis cache to improve test time.

- ConfigurationSystem/private/AddResourceAPI.py
resolves https://github.com/ic-hep/DIRAC/issues/83
> Fix bug when MaxCPUTime is None.

- ConfigurationSystem/Agent/AutoBdii2CSAgent.py
- ConfigurationSystem/private/AddResourceAPI.py
fixes https://github.com/ic-hep/DIRAC/issues/84
@sfayer please test and comment/deploy
> Get a fixed value of MaxProcessors from CS.

- ConfigurationSystem/private/AddResourceAPI.py
- ConfigurationSystem/private/AutoResourceTools/SETypes.py
@sfayer @marianne013 
I'm hoping that this patch will fix the issues that you have seen re same se host endpoint with multiple dirac se entries.
please test and merge
> Fix Dirac SE names for same host.

- ConfigurationSystem/Agent/AutoVac2CSAgent.py
- ConfigurationSystem/ConfigTemplate.cfg
- ConfigurationSystem/private/AddResourceAPI.py
- ConfigurationSystem/private/AutoResourceTools/ConfigurationSystem.py
This fixes https://github.com/ic-hep/DIRAC/issues/86
plus a free fix for the BDII agent thrown in :wink:
> Auto vac cs agent

- ConfigurationSystem/Agent/AutoBdii2CSAgent.py
- ConfigurationSystem/private/AddResourceAPI.py
- ConfigurationSystem/private/AutoBDIISEs.py
- ConfigurationSystem/private/AutoResourceTools/CETypes.py
This PR closes https://github.com/ic-hep/DIRAC/issues/87
@sfayer please give it a look over and test on the test server.
> Adding new update_ses function.

- ConfigurationSystem/private/UsersAndGroupsAPI.py
This fixes https://github.com/ic-hep/DIRAC/issues/98
> Add group static user support.

- ConfigurationSystem/Agent/AutoBdii2CSAgent.py
- ConfigurationSystem/private/AddResourceAPI.py
- ConfigurationSystem/private/AutoResourceTools/ConfigurationSystem.py
- ConfigurationSystem/private/AutoResourceTools/Glue2HTCondorAPI.py
This PR fixes https://github.com/ic-hep/DIRAC/issues/93
> Add Glue2 checking for HTCondor resources.

- ConfigurationSystem/private/AutoResourceTools/Glue2HTCondorAPI.py
This commit fixes https://github.com/ic-hep/DIRAC/issues/99
> Add CondorCEs to the site CE list.

- ConfigurationSystem/Agent/AutoBdii2CSAgent.py
- ConfigurationSystem/private/AddResourceAPI.py
- ConfigurationSystem/private/AutoBDIISEs.py
- ConfigurationSystem/private/AutoResourceTools/Glue2ARCAPI.py
- ConfigurationSystem/private/AutoResourceTools/Glue2HTCondorAPI.py
- ConfigurationSystem/private/AutoResourceTools/ldaptools.py
This PR fixes https://github.com/ic-hep/DIRAC/issues/101 and is built on https://github.com/ic-hep/GridPPDIRAC/pull/67
> Mock ldap utility

- ConfigurationSystem/private/AutoBDIISEs.py
- ConfigurationSystem/private/AutoResourceTools/Glue2ARCAPI.py
- ConfigurationSystem/private/AutoResourceTools/Glue2HTCondorAPI.py
- ConfigurationSystem/private/AutoResourceTools/ldaptools.py
@simon This is a hot fix. I think this will fix the issue you are seeing.... However I need to test if it breaks the other code where I had to switch from [0] to just the item itself. Feel free to test it for the SEs but I'll test it properly on Monday now.
> Fix bug in mock_ldap seach_s

- ConfigurationSystem/Agent/AutoBdii2CSAgent.py
- ConfigurationSystem/private/AddResourceAPI.py
- ConfigurationSystem/private/AutoResourceTools/Glue2ARCAPI.py
- ConfigurationSystem/private/AutoResourceTools/Glue2HTCondorAPI.py
This commit fixes https://github.com/ic-hep/DIRAC/issues/103
> Implement banned CEs and fixed max processors in ARC and HTCondor modules
